% Auto-generated by cameraCalibrator app on 30-Nov-2016
%-------------------------------------------------------


% Define images to process
imageFileNames = {'G:\9.26网络安全会议\右\1 (1).jpg',...
    'G:\9.26网络安全会议\右\1 (2).jpg',...
    'G:\9.26网络安全会议\右\1 (3).jpg',...
    'G:\9.26网络安全会议\右\1 (4).jpg',...
    'G:\9.26网络安全会议\右\1 (5).jpg',...
    'G:\9.26网络安全会议\右\1 (6).jpg',...
    'G:\9.26网络安全会议\右\1 (7).jpg',...
    'G:\9.26网络安全会议\右\1 (8).jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 20;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
